---
- name: Install Docker and python3
  become: yes
  hosts: Docker-server
  tasks:
    - name: Install Docker and python3
      vars:
        ansible_python_interpreter: /usr/bin/python
      apt:
        name: 
          - docker
          - python3
        update_cache: yes
        state: present

