---
- name: Ensure ssh connection is possible
  hosts: all
  gather_facts: False
  tasks:
    - name: ensuring the connection
      wait_for:
        port: 22
        host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
        search_regex: OpenSSH
        delay: 10
        timeout: 100
      vars:
        ansible_connection: local
        ansible_python_interpreter: /usr/bin/python
        
- name: Install Docker and python3
  become: yes
  gather_facts: False
  hosts: all
  tasks:
    - name: Install Docker and python3
      vars:
        ansible_python_interpreter: /usr/bin/python
      apt:
        name: 
          - docker
          - python3
          - python-pip
          - python3-pip
        update_cache: yes
        state: present
    - name: Add Docker GPG apt Key
      apt_key: 
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
 
    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present
 
    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install docker-compose
      get_url:
        url : https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x'

    - name: Install docker in python
      pip:
        name:
          - docker
          - docker-compose
        
- name: Start docker daemon
  become: yes
  hosts: all
  tasks:
    - name: Start docker daemon
      systemd:
        name: docker
        state: started
        
- name: Add azure user to docker group
  become: yes
  hosts: all
  tasks:
    - name: Add user
      user:
        name: azureuser
        groups: docker
        append: yes
    - name: Reconnect server session
      meta: reset_connection
